# Generated by Django 3.2.5 on 2021-07-26 16:51

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('account_id', models.IntegerField(unique=True)),
                ('limit', models.IntegerField()),
            ],
        ),
    ]
