# Generated by Django 3.2.5 on 2021-07-26 13:47

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
