apiVersion: v1
kind: Service
metadata:
  name: django-test-service
spec:
  selector:
    app: django-test-app
  ports:
    - protocol: "TCP"
      port: 8090
      targetPort: 8090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-test-deploy
  labels:
    app: django-test-app
spec:
  selector:
    matchLabels:
      app: django-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: django-test-app
    spec:
      containers:
        - name: django-test-app
          image: juandm93/spstest:latest
          ports:
            - containerPort: 8090
