# Generated by Django 3.2.5 on 2021-07-26 16:51

import accounts.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField()),
                ('accounts', djongo.models.fields.ArrayField(default=None, model_container=accounts.models.Account)),
            ],
        ),
    ]
